spring:
  application:
    name: star-maplestory

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas:
      - star

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/star
    initialization-mode: always
    schema: classpath:schema-init.sql
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8
    name: hikariCP
    hikari:
      maximum-pool-size: 10
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 2000
      validation-timeout: 1000
      idle-timeout: 0
      max-lifetime: 30000
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
      data-source-properties:
        serverTimezone: GMT+8
        useTimezone: true
        zeroDateTimeBehavior: round
        characterEncoding: utf8
        cachePrepStmts: true
        prepStmtCacheSize: 128
        prepStmtCacheSqlLimit: 1024
        useSSL: false
        useUnicode: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL55Dialect

logging:
  config: classpath:logback.xml
